#### ASSISNMENT 2 SOLUTION

Q 1. Explain the difference between a Python list and NumPy array in terms of memory usage and performance.Then, write a program that creates both and performs element wise multiplication.

  * Python List :-     
                   
     * Can store different data types     
     * Uses more memory                  
     * Slower for mathematical operations 
     * No direct element-wise operations 

  * NumPy Array :-

      * Stores only same data type
      * Use less memory
      * Faster for matheatical operation
      * Supports element wise operations

In [17]:
## PROGRAM EXAMPLE 
import numpy as np

# Python lists
list1 = [1, 2, 3]
list2 = [4, 5, 6]

# NumPy arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Element-wise multiplication
list_result = [list1[i] * list2[i] for i in range(len(list1))]
array_result = arr1 * arr2

print("List multiplication:", list_result)
print("NumPy Array multiplication:", array_result)


List multiplication: [4, 10, 18]
NumPy Array multiplication: [ 4 10 18]


Q 2.What is broadcasting in NumPy? Create a 3 X 3 NumPy array and add a 1D array to it using broadcating.Explain how NumPy applies the operation internally.

Ans - Broadcasting allows NumPy to perform operations on arrays of different shapes.

### Example :-

In [18]:

import numpy as np

A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

B = np.array([10, 20, 30])

result = A + B

print(result)


[[11 22 33]
 [14 25 36]
 [17 28 39]]


* Explaination:-

NumPy automatically repeats array B for each row like this:

[10 20 30]

[10 20 30]

[10 20 30]

Then it adds corresponding elements row-wise.

Q 3. What are the missing values in Pandas and how are they represented?
     Create a dataframe with missing values and write code to:
  * Detect missing values
  * Replace them with column mean

 Explain each step.

Ans - Missing values are empty or unknown data in a dataset.

They are represented as:

* NaN

* None

### Example:-

Creating data frame with missing values

In [19]:
import pandas as pd
import numpy as np

# Step 1: Create a dictionary with missing values (NaN)
data = {
    "Maths": [85, 90, np.nan, 75, 95],
    "Science": [80, np.nan, 70, 60, 85],
    "English": [np.nan, 88, 92, 79, 84]
}

# Step 2: Convert dictionary into DataFrame
df = pd.DataFrame(data)

print("Original DataFrame:")
print(df)


Original DataFrame:
   Maths  Science  English
0   85.0     80.0      NaN
1   90.0      NaN     88.0
2    NaN     70.0     92.0
3   75.0     60.0     79.0
4   95.0     85.0     84.0


Detect Missing Values

In [20]:
print("\nDetecting Missing Values:")
print(df.isnull())



Detecting Missing Values:
   Maths  Science  English
0  False    False     True
1  False     True    False
2   True    False    False
3  False    False    False
4  False    False    False


   Explaination
   * np.nan → Represents missing value

   * pd.DataFrame() → Creates a table

   * df.isnull() → Checks each cell

   * If value is missing → True

   * If value is present → False

Replace Missing Values with Column Mean

In [21]:
# Step 3: Replace missing values with column mean
df.fillna(df.mean(), inplace=True)

print("\nDataFrame After Replacing Missing Values:")
print(df)



DataFrame After Replacing Missing Values:
   Maths  Science  English
0  85.00    80.00    85.75
1  90.00    73.75    88.00
2  86.25    70.00    92.00
3  75.00    60.00    79.00
4  95.00    85.00    84.00


Explaination
* fillna(df.mean( )): Finds missing values

* Replaces them with the average of that column

* inplace=True - It updates the original DataFrame directly.


Q 4.Explain boolean indexing in NumPy or Pandas.
    Create a Dataframe wth atleast 5 columns and filter rows based on two conditions using logical operators.Explain how filtering works internally.

Ans - Boolean indexing is used to filter data using conditions.

Example:

In [22]:
import pandas as pd

data = {
    "Name": ["A", "B", "C", "D", "E"],
    "Age": [20, 25, 22, 30, 28],
    "Marks": [85, 60, 75, 90, 50],
    "City": ["Jaipur", "Delhi", "Jaipur", "Mumbai", "Delhi"],
    "Gender": ["F", "M", "F", "M", "F"]
}

df = pd.DataFrame(data)

# Filter rows where Age > 22 AND Marks > 70
filtered = df[(df["Age"] > 22) & (df["Marks"] > 70)]

print(filtered)


  Name  Age  Marks    City Gender
3    D   30     90  Mumbai      M


Explanation:

* Conditions return True or False

* Rows with True are selected

* & is used for AND condition

Q 5. What is the purpose of groupby() function in Pandas? Create a dataframe with categorical data (e.g depatment & salary) and calculate the average salary per department using groupby().Explain the output.

Ans - The groupby() function is used to group data based on a category and apply operations like sum, mean, or count.

Example:

In [23]:
import pandas as pd

data = {
    "Department": ["IT", "HR", "IT", "HR", "Finance"],
    "Salary": [50000, 40000, 60000, 45000, 70000]
}

df = pd.DataFrame(data)

# Calculate average salary per department
result = df.groupby("Department")["Salary"].mean()

print(result)


Department
Finance    70000.0
HR         42500.0
IT         55000.0
Name: Salary, dtype: float64


Explanation:

* Data is grouped by "Department"

* Mean salary is calculated for each department